name: Vercel Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.12'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Setup pnpm
      run: SHELL=/bin/bash pnpm setup

    - name: Add PNPM_HOME to PATH
      run: echo "export PATH=$(pnpm bin -g):\${PATH}" >> $GITHUB_ENV

    - name: Install dependencies
      run: pnpm install

    - name: Install Vercel CLI globally
      run: pnpm install -g vercel

    - name: Build and deploy
      run: pnpm run build && vercel --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
